version: "3"
services:
  broker:
    image: redis:5
  web:
    build: . # Current directory!
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - broker
