# Generated by Django 3.1.7 on 2021-11-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnbcrowconstant',
            old_name='transaction_fee',
            new_name='escrow_fee',
        ),
    ]
