# Generated by Django 3.1.7 on 2021-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20211102_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
