# Generated by Django 3.1.7 on 2021-11-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_order_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='maker',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='seller',
            new_name='taker',
        ),
        migrations.AddField(
            model_name='order',
            name='advertisement',
            field=models.ForeignKey(default='71427deb-fd86-4156-8abd-5fff209e90e7', on_delete=django.db.models.deletion.CASCADE, to='trades.advertisement'),
            preserve_default=False,
        ),
    ]
