# Generated by Django 3.1.7 on 2021-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20211104_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('ADMIN_COMPLETED', 'Admin Completed'), ('TAKER_CANCELLED', 'Taker Cancelled'), ('MAKER_CANCELLED', 'Maker Cancelled'), ('ADMIN_CANCELLED', 'Admin Cancelled')], default='OPEN', max_length=255),
        ),
    ]
